[package]
name = "packing"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[workspace]


[dependencies]
clap = "=3.0.0-beta.4"
getopts = "0.2"
